-- MySQL Script generated by MySQL Workbench
-- 06/04/17 05:52:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema machinemonitors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema machinemonitors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `machinemonitors` DEFAULT CHARACTER SET utf8 ;
USE `machinemonitors` ;

-- -----------------------------------------------------
-- Table `machinemonitors`.`supervisores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`supervisores` (
  `idSupervisor` INT(11) NOT NULL,
  `nombreSupervisor` VARCHAR(45) NOT NULL,
  `correoSupervisor` VARCHAR(60) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `celular` INT(9) NOT NULL,
  `status` ENUM('habilitado', 'desabilitado') NOT NULL,
  PRIMARY KEY (`idSupervisor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`empresas` (
  `idEmpresa` INT(11) NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `telefono` INT(9) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB
AUTO_INCREMENT = 302
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`zonas` (
  `idZona` INT(11) NOT NULL,
  `idEmpresa` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZona`),
  INDEX `idEmpresa` (`idEmpresa` ASC),
  CONSTRAINT `zonas_ibfk_1`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `machinemonitors`.`empresas` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`archivos` (
  `idArchivo` INT(11) NOT NULL,
  `idZona` INT(11) NOT NULL,
  `idSupervisor` INT(11) NOT NULL,
  `fechaSubida` DATE NOT NULL,
  `fechaDatos` DATE NOT NULL,
  `horaSubida` TIME NOT NULL,
  PRIMARY KEY (`idArchivo`),
  INDEX `idZona` (`idZona` ASC),
  INDEX `idSupervisor` (`idSupervisor` ASC),
  CONSTRAINT `archivos_ibfk_1`
    FOREIGN KEY (`idSupervisor`)
    REFERENCES `machinemonitors`.`supervisores` (`idSupervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `archivos_ibfk_2`
    FOREIGN KEY (`idZona`)
    REFERENCES `machinemonitors`.`zonas` (`idZona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`clientes` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(60) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`clientes_empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`clientes_empresas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idCliente` INT(11) NOT NULL,
  `idEmpresa` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCliente` (`idCliente` ASC),
  INDEX `idEmpresa` (`idEmpresa` ASC),
  CONSTRAINT `clientes_empresas_ibfk_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `machinemonitors`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clientes_empresas_ibfk_2`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `machinemonitors`.`empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`datos` (
  `idDato` INT(11) NOT NULL,
  `idArchivo` INT(11) NOT NULL,
  `patente` VARCHAR(6) NOT NULL,
  `hora` TIME NOT NULL,
  `latitud` FLOAT(10,6) NOT NULL,
  `longitud` FLOAT(10,6) NOT NULL,
  `motorFuncionando` INT(1) NOT NULL,
  `rpm` FLOAT NOT NULL,
  `gradosPalaFrontal` FLOAT NOT NULL,
  `gradosPalaTrasera` FLOAT NOT NULL,
  `cambio` INT(2) NOT NULL,
  `alturaPalaFrontal` FLOAT NOT NULL,
  `alturaPalaTrasera` FLOAT NOT NULL,
  PRIMARY KEY (`idDato`),
  INDEX `idArchivo` (`idArchivo` ASC),
  CONSTRAINT `datos_ibfk_1`
    FOREIGN KEY (`idArchivo`)
    REFERENCES `machinemonitors`.`archivos` (`idArchivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`maquinas` (
  `idMaquina` INT(11) NOT NULL,
  `idZona` INT(11) NOT NULL,
  `patente` VARCHAR(6) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `tara` INT(11) NOT NULL,
  `cargaMaxima` INT(11) NOT NULL,
  PRIMARY KEY (`idMaquina`),
  INDEX `idZona` (`idZona` ASC),
  CONSTRAINT `maquinas_ibfk_1`
    FOREIGN KEY (`idZona`)
    REFERENCES `machinemonitors`.`zonas` (`idZona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`resultados` (
  `idResultado` INT(11) NOT NULL,
  `idArchivo` INT(11) NOT NULL,
  `patente` VARCHAR(6) NOT NULL,
  `idMaquina` INT(11) NOT NULL,
  `registrado` INT(1) NOT NULL,
  `existeEnArchivo` INT(1) NOT NULL,
  `fechaDatos` DATE NOT NULL,
  `pRpm` FLOAT NOT NULL,
  `pGpf` FLOAT NOT NULL,
  `pGpt` FLOAT NOT NULL,
  `pApf` FLOAT NOT NULL,
  `pApt` FLOAT NOT NULL,
  `tRecorridos` FLOAT NOT NULL,
  `mediciones` INT(11) NOT NULL,
  PRIMARY KEY (`idResultado`),
  INDEX `idArchivo` (`idArchivo` ASC),
  CONSTRAINT `resultados_ibfk_1`
    FOREIGN KEY (`idArchivo`)
    REFERENCES `machinemonitors`.`archivos` (`idArchivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machinemonitors`.`supervisores_zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machinemonitors`.`supervisores_zonas` (
  `id` INT(11) NOT NULL,
  `idZona` INT(11) NOT NULL,
  `idSupervisor` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idZona` (`idZona` ASC),
  INDEX `idSupervisor` (`idSupervisor` ASC),
  CONSTRAINT `supervisores_zonas_ibfk_1`
    FOREIGN KEY (`idZona`)
    REFERENCES `machinemonitors`.`zonas` (`idZona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `supervisores_zonas_ibfk_2`
    FOREIGN KEY (`idSupervisor`)
    REFERENCES `machinemonitors`.`supervisores` (`idSupervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
